### ISSUE TITLE
overlay is not visible in modals.

### ISSUE THREAD

**Issue by albertolobrano** [vaadin/vaadin-combo-box#147]
The overlay is not displayed when the component is in a paper-dialog modal component.

**Comment by Saulis** [comment]
Hi and thanks for the report!

While waiting for the fix, you can workaround it by setting the overlay `z-index` to something higher than what `<paper-dialog>` uses (103)

```css
vaadin-combo-box-overlay {
  z-index: 200;
}
```
