### ISSUE TITLE
Add a custom property for overriding overlay max-height

### ISSUE THREAD

**Issue by Saulis** [vaadin/vaadin-combo-box#181]
Need a custom css property for overriding the `#scroller` `max-height` property, which is `65vh` by default.

**Comment by Saulis** [comment]
For a workaround, you can override the `max-height` with:

```css
vaadin-combo-box-overlay #scroller {
  max-height: XXX
}
```
