### ISSUE TITLE
css mix-in for items

### ISSUE THREAD

**Issue by depeele** [vaadin/vaadin-combo-box#242]
It would be great if there were a css mix-in for items to allow general theme-based styling of combo-box items.

Example:

``` css
#selector .item {
  cursor: pointer;
  padding: 13px 16px;
  color: var(--primary-text-color);
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;

  /* css mix-in */
  @apply(--vadin-combo-box-overlay-item);
}
```
