### ISSUE TITLE
Clear icon is shown when disabled

### ISSUE THREAD

**Issue by web-padawan** [vaadin/vaadin-combo-box#407]
### Description
If `vaadin-combo-box` has a value selected but is disabled, clear icon is shown (and expand icon is not). This looks buggy, why to show clear icon if we can't clear?

### Expected outcome
Icon should be hidden, e. g. 
```css
      :host([disabled]) paper-icon-button.clear-button,
      :host([disabled]) ::content paper-icon-button.clear-button  {
        display: none;
      }
```

### Actual outcome
Icon stays visible while combo box is disabled.

### Live Demo
Example: https://jsbin.com/veligoviza/1/edit?html,output
