### ISSUE TITLE
Feature request: add option to hide clear icon

### ISSUE THREAD

**Issue by web-padawan** [vaadin/vaadin-combo-box#424]
### Description
In some cases we expect to always have some value selected, e. g. user should not be allowed to clear, to emulate the same appearance as [paper-dropdown-menu](https://www.webcomponents.org/element/PolymerElements/paper-dropdown-menu) actually has.

I know that we can use `vaadin-combo-box-light` for that, but since the expected change is small, what about implementing it as a boolean property, e. g. 
```js
noClearIcon: {
  type: Boolean,
  reflectToAttribute: true
}
````

It should be as simple as adding a few CSS rules: 
```css
:host([no-clear-icon]) paper-input-container paper-icon-button.clear-button,
:host([no-clear-icon]) paper-input-container ::content paper-icon-button.clear-button {
  display: none;
}

:host([has-value][no-clear-icon]) #input {
  padding-right: 32px;
}
```
What do you think? Is this worth implementing? If so, I could submit a PR.
